### ISSUE TITLE
Demo issuer fails with gateway timeout

### ISSUE THREAD

**Issue by nedgar** [Sphereon-Opensource/did-siop-auth-web-demo#13]
I'm seeing frequent 504 gateway timeout errors with the demo issuer.

Steps:
- go to https://ssi.sphereon.com/demo/issuer/
- click the button at right, "With a wallet"
- scan the QR code with Sphereon app (I'm using the iOS version)

The app shows "Getting information...". After 30 secs or so, it shows an error popup with "Unable to retrieve information. Error: ...504 Gateway Time-out" (error body is in HTML, with tags showing).

![610E05E7-44BD-4E24-B8A3-3D58B5531C00_1_101_o](https://github.com/Sphereon-Opensource/OID4VC-demo/assets/692834/3fd234fb-d06d-41fb-ba13-c34764a2f740)

**Comment by nedgar** [comment]
The QR code encodes, e.g.: 
```json
{
  "correlationId": "bd33e0ca-228a-4659-9db8-9e26a7a4adde",
  "definitionId": "sphereonWallet",
  "authRequestURI": "openid-vc://?request_uri=https%3A%2F%2Fssi.sphereon.com%2Fagent%2Fsiop%2Fdefinitions%2FsphereonWallet%2Fauth-requests%2Fbd33e0ca-228a-4659-9db8-9e26a7a4adde",
  "authStatusURI": "https://ssi.sphereon.com/agent/webapp/auth-status"
}
```

The `request_uri` decoded is https://ssi.sphereon.com/agent/siop/definitions/sphereonWallet/auth-requests/bd33e0ca-228a-4659-9db8-9e26a7a4adde. From my laptop, I'm able to `curl` this OK (no gateway timeout).

**Comment by nklomp** [comment]
Sorry for the late reply.

This had to do with a bug in the well-known DID handling of the wallet. The low-level library we created for that has an option to pass in a DID resolver. If not provided the universal resolver is being used. Since that one has many issues, you are seeing this result. The latest wallet releases and the develop branch do not have these issues anymore. It is also fixed for this project in the develop branch.
